import {StyleSheet} from 'react-native';
import {Colors, Fonts, Metrics} from '../../theme';

export default StyleSheet.create({
  container: {flex: 1, backgroundColor: Colors.white, paddingHorizontal: 20},
  subConatiner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  stepButton: {flexDirection: 'row', alignItems: 'center'},
  stepsView: {
    borderWidth: 1,
    borderRadius: 50,
    height: 25,
    width: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  ImagePickerConatiner: {
    width: 92,
    height: 92,
    borderWidth: 1,
    borderColor: Colors.LIGHT_TONE,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderStyle: 'dashed',
  },
  cameraIcon: {height: 24, width: 24},
  uploadImageText: {
    textAlign: 'center',
    paddingTop: 10,
    fontFamily: Fonts.type.regular,
    fontSize: Fonts.size.size_14,
  },
  scrollContainer: {flex: 1, marginVertical: 30},
  subscriptionText: {
    fontFamily: Fonts.type.bold,
    fontSize: Fonts.size.size_18,
    color: Colors.black,
  },
  subsDescription: {
    marginTop: 10,
    fontFamily: Fonts.type.regular,
    fontSize: Fonts.size.size_14,
    color: Colors.black,
  },
  planContainer: {
    padding: 20,
    marginTop: 15,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: Colors.FIELD_BORDER,
  },
  titleAndPriceContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  planTitle: {
    fontFamily: Fonts.type.bold,
    fontSize: Fonts.size.size_18,
  },
  planPrice: {fontFamily: Fonts.type.bold, fontSize: Fonts.size.size_18},
  planPointContainer: {marginTop: 20, flexDirection: 'row'},
  planCheckImage: {
    width: 15,
    height: 15,
    marginRight: 10,
  },
  points: {fontFamily: Fonts.type.regular, fontSize: Fonts.size.size_14},
  textContainer: {flexDirection: 'row', justifyContent: 'space-between'},
  linkText: {
    fontFamily: Fonts.type.regular,
    fontSize: Fonts.size.size_14,
    color: Colors.black,
  },
  uploadContainer:{marginTop: 10},
  uploadText: {
    fontFamily: Fonts.type.regular,
    fontSize: Fonts.size.size_12,
    color: Colors.black,
    paddingBottom: 10,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    position: 'relative',
  },
  linkField: {
    flex: 1,
    borderWidth: 1,
    paddingVertical: 12,
    paddingLeft: 12,
    paddingRight: 40,
    borderRadius: 8,
    borderColor: Colors.FIELD_BORDER,
    height: 48,
  },
  linkIcon: {
    position: 'absolute',
    right: 10,
    top: 12,
    height: 24,
    width: 24,
  },
  deleteIcon:{
    position: 'absolute',
    right: 10,
    top: 12,
  }
});
